import {Injectable} from '@angular/core';
import {Verband} from './verband';
import {Veranstaltung} from './veranstaltung';

@Injectable({
  providedIn: 'root'
})

export class Verbandservice {

  private verbaende: Verband[] = [
    {id: 1, name: 'BUND Kreisverband Main-Kinzig', pic: '../assets/pic/BUND.png', description:'Der Bund für Umwelt und Naturschutz Deutschland e.V. (BUND) ist ein überparteilicher und überkonfessioneller Umwelt- und Naturschutzverband. Im Main-Kinzig-Kreis sind derzeit 3 BUND-Ortsverbände aktiv: Ortsverband Gelnhausen mit den Gemeinden Biebergemünd, Gründau und Linsengericht, Ortsverband Schlüchtern mit Sinntal und Steinau und Ortsverband Nidderau.', taetigkeit: ['Schutz von Amphibien, Vögel und Fledermäusen.', 'Streuobstbestände pflegen, Blühflächen für Bienen und Schmetterlinge anlegen.', 'Unterstützung von Schulgärten und Angebote für Kinder die Natur zu erkunden.', 'Beratung und Planung für eigene (Naturgarten)-Projekte.', 'Main-Kinzig blüht: Pflege angelegter Flächen.', 'Beteiligung an Main.Kinzig.Blüht.Net.'], veranstaltung: [], kontakt: [] },
    {id: 2, name: 'Gesellschaft für Naturschutz und Auenentwicklung (GNA)', pic: '../assets/pic/GNA logo.jpg', description:'Die gemeinnützige Gesellschaft für Naturschutz und Auenentwicklung (GNA) setzt sich für den Schutz, den Erhalt und die Entwicklung der Lebensräume wild­lebender Tier- und Pflanzengesellschaften ein. Zu unseren Projekten zählen die Renaturierung von Fließgewässern, die naturnahe Entwicklung der Kinzigauen, der Natur-, Arten- und Biotopschutz sowie die Umweltbildung. So fördern wir seit langem ganz bewusst den Nachwuchs. Unser langfristiges Ziel ist es, die Naturbildung für Kinder, Jugendliche und Erwachsene in den kommenden Jahren weiter auszubauen.', taetigkeit: ['Artenschutzprojekte für Eisvogel, Kiebitz, Bekassine, Storch, Biber und Fischotter', 'Beweidung und Weiterentwicklung Feuchtgebiet Herrenbruch', 'Biotopverbünde Laubfrosch und Gelbbauchunke', 'Quellensicherung und Entwicklung der Biodiversität im Brachttaler „Fußloch“'], veranstaltung: [], kontakt: [] },
    {id: 3, name: 'Hessische Gesellschaft für Ornithologie und Naturschutz e.V. (HGON)', pic: '../assets/pic/HGON_Logo.jpg', description: 'Die HGON ist einer der acht nach Bundesnaturschutzgesetz anerkannten Naturschutzverbände in Hessen. Die ehrenamtlichen HGON Mitglieder sind auf Landkreisebene in sogenannten Arbeitskreisen (AK) organisiert. Der Arbeitskreissprecher ist der verlängerte Arm des Landesvorstands. Neben den Arbeitskreisen können jedoch auch einzelne Arbeitsgruppen und Netzwerke von HGON Mitgliedern in den AK oder auf Landesebene aktiv sein. Arbeitskreissprecher im Main-Kinzig-Kreis ist Andreas Höfler. Ihren Sitz hat der AK Main-Kinzig im Naturschutzzentrum Rodenbach.', taetigkeit: ['Natur- und Artenschutzprojekte', 'Umweltbildung', 'Beteiligungen als Träger öffentlicher Belange'], veranstaltung: [], kontakt: []},
    {id: 4, name: 'Imkerverein Jossgrund', pic: '../assets/pic/imker jossgrund.png', description: '', taetigkeit: ['Bienenpflege', 'Honigverarbeitung', 'Engagement in Natur und Umweltschutz'], veranstaltung: [], kontakt: []},
    {id: 5, name: 'Imkerverein Steinau e.V.', pic: '../assets/pic/Imkerverein Steinau - Logo.jpg', description: 'Der Imkerverein Steinau steht zusammen mit seinen Nachbarvereinen für die Förderung des Natur- und Landschaftsschutzes.', taetigkeit: ['Zucht, Haltung und Verbreitung der Carnica-Honigbiene','Praktische Anleitung und Ausbildung der Imkerschaft am Lehrbienenstand','Unterhaltung einer Belegstelle','Beratung rund um das Thema Imkerei für Imker und alle Interessengruppen','Unterstützung bei der Anlage von Blühflächen'], veranstaltung: [], kontakt: []},
    {id: 6, name: 'Kreisbauernverband Main-Kinzig e.V.', pic: '', description: '', taetigkeit: ['Berufsständische Interessensvertretung regionaler landwirtschaftlicher Betriebe', 'Regelmäßige Information unserer Mitglieder über aktuellen Themen aus den Bereichen Agrarpolitik, Märkte, Tier- und Pflanzenproduktion', 'Persönliche Rechtsberatung', 'Fort- und Weiterbildung mit Unterstützung des Hessischen Bauernverbands oder in Kooperation mit weiteren kompetenten Institutionen und Ämtern', 'Stärkung der Landwirtschaft durch Sensibilisierung von Kindern und Jugendliche, sowie Verbraucher im Allgemeinen für landwirtschaftliche Produkte und Leistungen, zum Beispiel durch Programme wie „Bauernhof als Klassenzimmer“ oder „Tag des offenen Hofes“.'], veranstaltung: [], kontakt: []},
    {id: 7, name: 'Landfrauenverein Altengronau', pic: '../assets/pic/landfrauen altengronau logo.jpg', description: 'Der Landfrauenverein Altengronau wurde im Jahre 1977 gegründet und zählt heute 116 Mitglieder.', taetigkeit: ['Vorträge zu den Themen: Ernährung, Gesundheit, Garten, Natur, Umwelt, Altersvorsorge mit Gastreferenten/innen', 'Dorfleben mitgestalten bei Kirmes, Schwimmbadfest, Weihnachtsmarkt, Blutspendeterminen', '    • Vereinsausflüge, Wanderungen, Fahrradtouren, Kräuterführungen, Betriebsbesichtigungen', 'Theaterbesuche, Lesungen, Kreatives', 'Gesellige Vereinsveranstaltungen: Adventsfeier, Kreppelkränzchen, Grillfest', 'Schachblumenfest organisieren und durchführen', 'Halbjahresprogramm/Jahresprogramm erstellen'], veranstaltung: [], kontakt: []},
    {id: 8, name: 'Landschaftspflegeverband Main-Kinzig-Kreis e.V.', pic: '../assets/pic/LPV Logo.jpg', description: 'Der Landschaftspflegeverband ist ein freiwilliger Zusammenschluss von Landwirtschaft, Kommunalpolitik und Naturschutz, die gleichberechtigt tätig sind und gemeinsam Projekte zum Schutz unserer Natur- und Kulturlandschaften umsetzten.', taetigkeit: ['Pflege und Erhalt von Streuobstbeständen', 'Herstellung von Ökopunkten für Kommunen und Privatpersonen', 'Artenschutzprojekte, z.B. Wendehals, Arnika', 'Bergwinkelgrün, Main.Kinzig.Blüht.Netz', 'Unterstützung bei Ausgleichsmaßnahmen'], veranstaltung: [], kontakt: []},
    {id: 9, name: 'LERNFELD LANDWIRTSCHAFT', pic: '../assets/pic/Lernfeld Landwirtschaft - Logo.jpg', description: 'LERNFELD LANDWIRTSCHAFT als Projekt des Main-Kinzig-Kreises, um Schulklassen und KITA-Gruppen einen Besuch auf dem Bauernhof zu ermöglichen und die landwirtschaftliche Produktion kennen zu lernen.', taetigkeit: ['Bauernhofpädagogik', 'außerschulisches Lernen (Landwirtschaft und Lebensmittelherstellung)', 'Öffentlichkeitsarbeit für die Landwirtschaft'], veranstaltung: [], kontakt: []},
    {id: 10, name: 'NABU MKK e. V.', pic: '../assets/pic/nabu_mkk.png', description: 'Kreisverband MKK des NABU Naturschutzbund Deutschland e. V.. Der NABU ist im Main-Kinzig-Kreis mit dem Kreisverband und zahlreichen örtlichen NABU-Gruppen vertreten. Seit mehr als 50 Jahren setzt sich der NABU im Main-Kinzig-Kreis für den Schutz unserer heimischen Natur und Umwelt ein. Viele weitere Informationen finden Sie unter WWW.NABU-MKK.de.', taetigkeit: ['Naturschutz', 'Artenschutz', 'Öffentlichkeitsarbeit'], veranstaltung: [], kontakt: []},
    {id: 11, name: 'Naturschutzfreunde Elm', pic: '../assets/pic/naturschutzfreunde elm - logo.jpg', description: 'Der Verein wurde 1986 gegründet und hat fast 100 Mitglieder. Damals hatten sich die Leute bereits Sorgen um die Natur rund um Elm gemacht.', taetigkeit: ['Pflege von Kalkmagerrasen (hier kommen Küchenschellen, verschiedene Orchideenarten, Berganemonen und Enziane vor)', 'Pflege von Tümpeln und Bächen für Amphibien', 'Erhalt und Pflege von Streuobstbeständen', 'aufhängen und reinigen von Nistkästen', 'Erhalt und Pflege von Hecken', 'Stärkung des Umweltbewusstseins der Bevölkerung'], veranstaltung: [], kontakt: []},
    {id: 12, name: 'Natur- und Vogelschutzgruppe Bad Orb e.V.', pic: '../assets/pic/nvsg bad orb.png', description: 'Der Verein besteht seit 1954 und hat 248 Mitglieder. Zweck ist die Förderung des Naturschutzes und der Landschaftspflege. Insbesondere der freilebenden Vogelwelt, Fledermäuse u. Amphibien und Erhalt und Schaffung der Lebensgrundlage gefährdeter Tiergruppen.', taetigkeit: ['Anschaffung, Unterhalt und Pflege von ca. 850 Nistkästen, Bruthilfen für Insekten, Schwalbenhaus in Planung, Betreuung von Blühwiesen, Betreuung des vereinseigenen Naturlehrpfades in Bad Orb', 'Unterhalt und Pflege von 16 Großraumfutterkästen, Winterfütterung', 'Neuanlage und Pflege von diversen Biotopteichen für Amphibien, umsetzen von Froschlaich, Eintiefen der Teiche, Reinigung im Herbst von Gras usw.', 'Waldführungen, Lehrwanderungen, Gewässeruntersuchung usw. für Kinder auch im Rahmen des Ferienpasses der Stadt Bad Orb auch mit Fremdreferenten, die wir bezahlen. Heranführen der Jugend an den Naturschutz.', 'Vogelstimmenwanderungen, Fledermausexkursionen, Schmetterlinge bestimmen für Erwachsene und Familien'], veranstaltung: [], kontakt: []},
    {id: 13, name: 'Naturpark Hessischer Spessart', pic: '../assets/pic/naturpark.png', description: 'Der Zweckverband wurde 1963 gegründet und ist der Zusammenschluss von 15 Gemeinden und Gemeindeverbänden und dem Landkreis.', taetigkeit: ['Den Naturpark als Erholungsgebiet zu erschließen und den Menschen eine naturnahe Erholung zu ermöglichen', 'Schaffung und Unterhaltung von Wanderwegen und Parkplätzen sowie die Förderung aller dem Wandern und der naturnahen Erholung dienenden Maßnahmen und Einrichtungen innerhalb des Naturparks.', 'Betreuung der ehrenamtlichen Naturparkführer/innen', 'Erstellen des Jahresprogramms und Ankündigen der Veranstaltungen in Print- und Online-Medien', 'Gestaltung, Erhalt und Pflege des Naturparks Spessart mit dem Ziel die heimische Tier- und Pflanzenwelt zu schützen, die Landschaft zu pflegen und zu gestalten und die ökologische Ausgleichsfunktion dieses Gebietes zu erhalten und zu fördern'], veranstaltung: [], kontakt: []},
    {id: 14, name: 'Ökologische Forschungsstation Schlüchtern e.V. (ÖFS)', pic: '../assets/pic/öfs - logo.jpg', description: 'Die Ökologische Forschungsstation Schlüchtern ist eine Arbeitsgruppe, die aus der ehemaligen Ökologischen Außenstelle der Goethe-Universität Frankfurt hervorgegangen ist und seit 2003 als unabhängige Institution existiert. Zentrale Punkte der Arbeit sind die wissenschaftliche Datenerhebung zu ökologischen Fragestellungen, Naturschutz und Naturpädagogik.', taetigkeit: ['Wissenschaftliche Arbeit: Seit Beginn der 1970er Jahre werden hier standardisiert Daten zu höhlennutzenden Tierarten (Singvögel, Kleinsäuger, Insekten) aufgenommen. Der hier angewandte Ganzjahresansatz sowie Kontinuität und Datenfülle dieses Projekts sind europaweit einzigartig.', 'Naturpädagogik: Das Weitergeben von Wissen über unsere Umwelt ist uns ein besonderes Anliegen. Neben langjährigen Kooperationen mit Schulen bieten wir ein umfangreiches Programm mit altersspezifischen naturpädagogischen Kursen an. Dazu stehen hier BiologInnen sowie ein ausgebildeter Wildnispädagoge zur Verfügung.', 'Naturschutz: Das Bewahren und Wiederherstellen intakter Biotope ist eine Aufgabe, die zunehmend wichtiger wird. Wir haben uns besonders auf den Lebensraum Streuobstwiese konzentriert, der einer der artenreichsten unserer heimischen Habitate ist. Zudem pflanzen und pflegen wir Hecken zur Vernetzung von Lebensräumen, engagieren uns auf vielfältige Weise für solitäre Insekten und arbeiten auch beratend (z.B. Konzepte für Zukunftswälder, Anpflanzungen etc.)'], veranstaltung: [], kontakt: []},
    {id: 15, name: 'RFC Roßbach/Spessart e.V.', pic: '../assets/pic/rfc roßbach.png', description: 'Der RFC Roßbach/Spessart e.V. hat seinen Sitz in Biebergemünd-Roßbach und wurde 1979 gegründet. Momentan zählt der Verein 157 Mitglieder, die als Leistungssportler oder Amateure wie auch im Breitensport in den Radsportarten Rennrad, Mountainbike und Radcross aktiv sind.', taetigkeit: ['regelmäßige Radtreffs', 'Jugendarbeit in den Bereichen MTB und Rennrad findet durch regelmäßige Treffs/Training und Teilnahme an Events und Radrennen statt.', 'gemeinsame Trainingslager, mehrtägige Etappenfahrten und Wanderungen', 'Aktionen und Projekte auch außerhalb des Radsports', 'Teilnahme an landes- und bundesweitern Wettbewerben, wie z.B. der Enduro One Serie'], veranstaltung: [], kontakt: []},
    {id: 16, name: 'Schulbauerndorf Weichersbach', pic: '../assets/pic/schulbauerndorf-weichersbach-logo.jpg', description: 'In Weichersbach (Sinntal) haben sich Bauern, Mühlenbesitzer, Forstwirtschaftler, Handwerker, Dienstleister und Privatpersonen zusammen getan, um Dorfleben und unberührte Natur zu präsentieren. So entsteht ein Erfahrungs- und Erlebnisort für alle mit Interesse an Landwirtschaft, altem und neuem Handwerk, Heimatkultur, Natur und Umwelt sowie dörflichem Zusammenleben. Aus Mitteln der Dorferneuerung wurde uns eine Entwicklungsstudie „Vom Schulbauerndorf zum Natur- und Erlebnisdorf“ finanziert. Ein halbes Dutzend Mitmach-Angebote sind über die Bildungspartner Main-Kinzig GmbH oder auch direkt buchbar. Zielgruppe sind je nach Angebot Kinder und Jugendliche, Erwachsene, Familien, Vereine oder sonstige Gruppen.', taetigkeit: ['Dorfleben', 'Natur', 'Handwerkskunst', 'Erfahrung-Erlebnis-Erholung', 'Bildung und Kultur'], veranstaltung: [], kontakt: []},
    {id: 17, name: 'Streuobstfreunde Schöneck e.V.', pic: '../assets/pic/streuobstfreunde schöneck.jpg', description: '', taetigkeit: ['Schnittkurse'], veranstaltung: [], kontakt: []},
    {id: 18, name: 'Tier- und Naturschutz Unterer Vogelsberg e. V. (TiNa)', pic: '../assets/pic/tina - logo.png', description: '', taetigkeit: ['Katzenschutz: Vermittlung von Katzen, Kastration verwildeter Katzen u.a.', 'Aufbau eines Netzwerks von Pflegestellen', 'Wildtierschutz im allgemeinen und Kitzrettung (www.kitzrettung-hilfe.de)', 'Müllvermeidung'], veranstaltung: [], kontakt: []},
    {id: 19, name: 'Turnverein 1868 e.V. Bad Orb', pic: '../assets/pic/TV Bad Orb.png', description: 'Im Jahr 2018 feierte der Turnverein 1868 e. V. Bad Orb sein 150-jähriges Bestehen. Als der älteste und mitgliedsstärkste Verein in unserem Heimatort tragen die Turnerinnen und Turner Jahr für Jahr zu einem umfangreichen sportlichen und kulturellen Programm bei. Durch das große Angebot an Kurs- und Freizeitangeboten ermöglichen wir allen Interessierten, sich im Breiten- und Spitzensport, kulturell und/oder musikalisch zu betätigen, neue Kontakte zu knüpfen und aktiv am Vereinsleben teilzunehmen.', taetigkeit: ['Tischtennis', 'Triathlon', 'MTB', 'Blasorchester', 'Handball'], veranstaltung: [], kontakt: []},
    {id: 20, name: 'Vogelschutzgruppe Hasselroth e. V.', pic: '', description: 'Wir sind ein selbständiger Verein und gemeinnützig. Wir verfolgen Ziele im Vogel- und Naturschutz, ebenso Pflege von Streuobstwiesen, Gebieten in der Gemarkung, Feldholzinseln.', taetigkeit: ['Vogelschutz', 'Umweltschutz', 'allgemeine Themen des Umweltschutzes z. B. Aquakulturen, Wasser und Landschaftsschutz', 'Jugend- und Kindergruppe - die Mitglieder werden an den Umweltschutz herangeführt.'], veranstaltung: [], kontakt: []}
  ];

  private veranstaltungen: Veranstaltung[];

  // tslint:disable-next-line:no-empty
  constructor() { }

  getVerbaende(): Verband[] {
    return this.verbaende;
  }

  getVerband(id: number): Verband {
    return this.verbaende.find(v => v.id === id);
  }

  getVeranstaltungen(): Veranstaltung[] {
    return this.veranstaltungen;
  }

  getVeranstaltung(id: number): Veranstaltung {
    return this.veranstaltungen.find(v => v.id === id);
  }
}
